# Generated by Django 3.2.23 on 2024-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paper_type',
            field=models.CharField(choices=[('matt', 'Matt Paper'), ('gloss', 'Gloss Paper')], default='matt', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], default='A4', max_length=10),
        ),
    ]
