# Generated by Django 3.2.23 on 2024-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240205_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paper_type',
        ),
        migrations.AddField(
            model_name='product',
            name='paper',
            field=models.CharField(choices=[('matt', 'Matt Paper'), ('gloss', 'Gloss Paper')], default='MATT', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], default='A4', max_length=5),
        ),
    ]
